### ISSUE TITLE
It does not retain saved parameters

### ISSUE THREAD

**Issue by PepeCobain** [rajeshca911/Executable-Decryptor-UI#1]
Once the IP and Port parameters are changed in the 'Extra' section, it does not retain them even though it shows the message of changed values and reverts them back to the default state, setting the IP to 192.168.0.105. Please check if it retains the value also on the main screen, or if the changed IP is only apparent and not actually functioning. Same thing for "port". Thanks

https://github.com/rajeshca911/Executable-Decryptor-UI/assets/72492818/9f139631-d2d8-4c23-adc8-6daadfd13ee7

**Comment by PepeCobain** [comment]
Even if you change inside "Executable Decryptor UI.exe.config" doesn't work

**Comment by rajeshca911** [comment]
Thanks for reporting, fixed the issue
